# command line: main.py --phase test --config ./config/uav_csv2/motion_6.yaml --work-dir ../GS-B/mix_motion_6 --weights ./temp/mix_motion_6/runs-90-11700.pt

base_lr: 0.2
batch_size: 128
config: ./config/uav_csv2/motion_6.yaml
device: 0
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
ignore_weights: []
log_interval: 100
model: model.ske_mixf.Model
model_args:
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  k: 6
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 90
num_worker: 4
optimizer: SGD
phase: test
print_log: true
save_epoch: 30
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 35
- 55
- 75
test_batch_size: 128
test_feeder_args:
  bone: false
  data_path: ../../data/test_joint.npy
  debug: false
  label_path: ../../data/test_C_label.npy
  p_interval:
  - 0.95
  split: test
  vel: true
  window_size: 64
train_feeder_args:
  bone: false
  data_path: ../../data/train_joint1.npy
  debug: false
  label_path: ../../data/train_label1.npy
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: true
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0005
weights: ./temp/mix_motion_6/runs-90-11700.pt
work_dir: ../GS-B/mix_motion_6
