# python3 main.py --config ./config/uav_csv2/motion_2.yaml --work-dir ./work_dir/motion_2
# python3 main.py --config ./config/uav_csv2/motion_2.yaml --work-dir ./temp/motion_2 --weights ./work_dir/motion_2/runs-109-14170.pt --phase test
# python3 main.py --config ./config/uav_csv2/motion_2.yaml --work-dir ../GS-B/infogcn_motion_2 --weights ./work_dir/motion_2/runs-109-14170.pt --phase test



# feeder
feeder: feeders.feeder_uav.Feeder

# train
#data_path: ../../data/train_joint1.npy
#label_path: ../../data/train_label1.npy

# Test
#data_path: ../../data/val_joint.npy
#label_path: ../../data/val_label.npy
data_path: ../../data/test_joint.npy
label_path: ../../data/test_C_label.npy
window_size: 64
random_rot: True
use_vel: True
use_angle: False

# model
num_class: 155
num_point: 17
num_person: 2
graph: graph.uav.Graph
k: 2
in_channels: 3
cl_mode: Null

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [90, 100]
warm_up_epoch: 5

# training
device: 0
batch_size: 128
test_batch_size: 128
num_epoch: 110
nesterov: True

half: True