# python main.py --config ./config/uav_csv2/angle_1.yaml --work-dir ./temp/mix_angle_1
# python main.py --phase test --config ./config/uav_csv2/angle_1.yaml --work-dir ../GS-B/mix_angle_1 --weights ./temp/mix_angle_1/runs-90-11700.pt

# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: ../../data/train_angle.npy
  label_path: ../../data/train_label1.npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: False
  p_interval: [0.5, 1]
  vel: False
  bone: False
  use_angle: True

test_feeder_args:
  #data_path: ../../data/val_angle.npy
  #label_path: ../../data/val_label.npy
  data_path: ../../data/test_angle.npy
  label_path: ../../data/test_C_label.npy
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  use_angle: True
  debug: False

# model
model: model.ske_mixf.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'
  k: 1
  in_channels: 9

#optim
weight_decay: 0.0005
base_lr: 0.2
step: [35, 55, 75]
warm_up_epoch: 5

# training
device: 0
batch_size: 64
test_batch_size: 128
num_epoch: 90
nesterov: True
