# python main.py --config ./config/uav_csv2/motion_1.yaml --work-dir ./temp/mix_motion_1
# python main.py --phase test --config ./config/uav_csv2/motion_1.yaml --work-dir ../GS-B/mix_motion_1 --weights ./temp/mix_motion_1/runs-90-11700.pt


# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: ../../data/train_joint1.npy
  label_path: ../../data/train_label1.npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: True
  bone: False

test_feeder_args:
  # data_path: ../../data/val_joint.npy
  # label_path: ../../data/val_label.npy
  data_path: ../../data/test_joint.npy
  label_path: ../../data/test_C_label.npy
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: True
  bone: False
  debug: False

# model
model: model.ske_mixf.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'
  k: 1

#optim
weight_decay: 0.0005
base_lr: 0.2
step: [35, 55, 75]
warm_up_epoch: 5

# training
device: 0
batch_size: 128
test_batch_size: 128
num_epoch: 90
nesterov: True
